name: dz3_example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  collection: ^1.18.0
  pub_api_client: ^2.6.0
  pub_semver: ^2.1.4
  pubspec: ^2.3.0
  z3:
    path: ../dz3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
