name: z3
description: High-level bindings to the Z3 SMT solver.
repository: https://github.com/pingbird/dz3

version: 1.0.0

environment:
  sdk: '>=3.0.0-290.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  ffi: ^2.1.0
  pub_semver: ^2.1.1
  package_config: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^9.0.1
  dz3_gen:
    path: ../dz3_gen
  build_runner: ^2.0.0
  file: ^7.0.0

flutter:
  uses-material-design: true

ffigen:
  output:
    bindings: 'lib/z3_ffi.dart'

  llvm-path:
    - 'C:\Program Files\LLVM'

  headers:
    entry-points:
      - '...\z3\src\api\z3.h'
      - '...\z3\src\api\*.h'

  functions:
    rename:
      'Z3_(.+)': '$1'

  structs:
    rename:
      'Z3_(.+)': '$1'
    member-rename:
      '.+':
        'Z3_(.+)': '$1'

  enums:
    member-rename:
      '.+':
        'Z3_(.+)': '$1'

  name: 'Z3Lib'

